-- [nfnl] fnl/easilok/plugins.fnl
local Plug = vim.fn["plug#"]
vim.call("plug#begin")
Plug("tpope/vim-fugitive")
Plug("tpope/vim-unimpaired")
Plug("lewis6991/gitsigns.nvim")
Plug("tpope/vim-dispatch")
Plug("junegunn/gv.vim")
Plug("tpope/vim-repeat")
Plug("tpope/vim-eunuch")
Plug("tpope/vim-abolish")
Plug("tpope/vim-surround")
Plug("tpope/vim-endwise")
Plug("lervag/vimtex")
Plug("christoomey/vim-tmux-navigator")
Plug("neovim/nvim-lspconfig")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-path")
Plug("hrsh7th/cmp-cmdline")
Plug("onsails/lspkind.nvim")
Plug("folke/trouble.nvim")
Plug("j-hui/fidget.nvim")
Plug("nvim-treesitter/nvim-treesitter", {["do"] = ":TSUpdate"})
Plug("nvim-treesitter/nvim-treesitter-context")
Plug("nvim-treesitter/nvim-treesitter-textobjects")
Plug("https://gitlab.com/HiPhish/rainbow-delimiters.nvim.git")
Plug("folke/which-key.nvim")
Plug("lukas-reineke/indent-blankline.nvim")
Plug("nvim-lua/plenary.nvim")
Plug("ibhagwan/fzf-lua", {["branch:"] = "main"})
Plug("nvim-telescope/telescope.nvim")
Plug("nvim-telescope/telescope-fzf-native.nvim", {["do"] = "make"})
Plug("ThePrimeagen/harpoon", {branch = "harpoon2"})
Plug("nvim-lualine/lualine.nvim")
Plug("kyazdani42/nvim-web-devicons")
Plug("akinsho/bufferline.nvim", {["tag:"] = "*"})
Plug("stevearc/oil.nvim")
Plug("mfussenegger/nvim-dap")
Plug("nvim-neotest/nvim-nio")
Plug("rcarriga/nvim-dap-ui")
Plug("theHamsta/nvim-dap-virtual-text")
Plug("williamboman/mason.nvim")
Plug("jay-babu/mason-nvim-dap.nvim")
Plug("folke/todo-comments.nvim")
Plug("L3MON4D3/LuaSnip", {tag = "v2.*"})
Plug("rafamadriz/friendly-snippets")
Plug("saadparwaiz1/cmp_luasnip")
Plug("folke/tokyonight.nvim", {branch = "main"})
Plug("srt0/codescope.nvim")
Plug("shaunsingh/nord.nvim")
Plug("sbdchd/neoformat")
Plug("junegunn/fzf", {dir = "~/.fzf", ["do"] = "./install --all"})
Plug("lervag/wiki.vim")
Plug("lervag/lists.vim")
Plug("itchyny/calendar.vim")
Plug("epwalsh/obsidian.nvim")
Plug("instant-markdown/vim-instant-markdown", {["for"] = {"markdown", "wiki"}, ["do"] = "npm install"})
Plug("MeanderingProgrammer/render-markdown.nvim")
Plug("godlygeek/tabular")
Plug("mbbill/undotree")
Plug("notjedi/nvim-rooter.lua")
Plug("tpope/vim-obsession")
Plug("tpope/vim-dadbod")
Plug("kristijanhusak/vim-dadbod-ui")
Plug("kristijanhusak//vim-dadbod-completion", {["for"] = {"sql", "mysql", "plsql"}})
Plug("AndrewRadev/linediff.vim")
Plug("mechatroner/rainbow_csv")
Plug("skywind3000/asyncrun.vim")
Plug("LunarVim/bigfile.nvim")
Plug("folke/zen-mode.nvim")
Plug("j-morano/buffer_manager.nvim")
Plug("pmizio/typescript-tools.nvim")
Plug("Olical/conjure")
Plug("PaterJason/cmp-conjure")
Plug("Olical/nfnl")
Plug("gpanders/nvim-parinfer")
Plug("olimorris/codecompanion.nvim")
vim.call("plug#end")
return {}
